name: constant_keys_generator
description: A genarator for create constant keys file from json file
version: 1.0.0
repository: https://github.com/TKSVN/constant_keys_generator

environment:
  sdk: '>=3.4.4 <4.0.0'

# Add regular dependencies here.
dependencies:
  glob: ^2.1.2
  yaml: ^3.1.2
  build: ^2.4.1

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

